version: "3"

services:
  app:
    image: node:18-alpine
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${APP_FORWARDED_PORT:-80}:${APP_PORT:-3000}"
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - ./src:/app
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8.1
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "${DB_FORWARDED_PORT:-3306}:${DB_PORT:-3306}"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d

volumes:
  db-data:
